#!/bin/bash
set -e

root="${PWD}"

echo "Build generate-translations architect ..."
cd projects/thymesave/translations/generate-translations-report
tsc

echo "Build generate-ingredient architect ..."
cd "${root}"
cd projects/thymesave/ingredients/generate-ingredient-report
tsc

echo "Compile report script ..."
cd "${root}"
tsc

echo "Generating json reports ..."
cd "${root}"
ng run @thymesave/translations:generate-report
ng run @thymesave/ingredients:generate-report

echo "Run report generation ..."
cd "${root}"
node "$(dirname "$0")/index.js"
