#!/bin/bash
TSC_VERSION="2.0.4"
set -e

root="${PWD}"

echo "Build generate-translations architect ..."
cd projects/thymesave/translations/generate-translations-report
npx tsc@"${TSC_VERSION}"

echo "Build generate-ingredient architect ..."
cd "${root}"
cd projects/thymesave/ingredients/generate-ingredient-report
npx tsc@"${TSC_VERSION}"

echo "Compile report script ..."
cd "${root}"
npx tsc@"${TSC_VERSION}"

echo "Generating json reports ..."
cd "${root}"
ng run @thymesave/translations:generate-report
ng run @thymesave/ingredients:generate-report

echo "Run report generation ..."
cd "${root}"
node "$(dirname "$0")/index.js"
