#!/bin/bash
set -e

root="${PWD}"

echo "Build generate-translations architect ..."
cd ../../projects/thymesave/translations/generate-translations-report
tsc

cd "${root}"

echo "Build generate-ingredient architect ..."
cd ../../projects/thymesave/ingredients/generate-ingredient-report
tsc

echo "Compile report script ..."
cd "${root}"
tsc

echo "Generating json reports ..."
cd ../..
ng run @thymesave/translations:generate-report
ng run @thymesave/ingredients:generate-report

echo "Run report generation ..."
cd "${root}"
node index.js
