version: 2
updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: weekly
    reviewers:
      - thymesave/silverware
  - directory: /projects/thymesave/core
    package-ecosystem: npm
    schedule:
      interval: weekly
    reviewers:
      - thymesave/silverware
  - directory: /projects/thymesave/ingredients
    package-ecosystem: npm
    schedule:
      interval: weekly
    reviewers:
      - thymesave/silverware
  - directory: /projects/thymesave/plugin
    package-ecosystem: npm
    schedule:
      interval: weekly
    reviewers:
      - thymesave/silverware
  - directory: /projects/thymesave/translations
    package-ecosystem: npm
    schedule:
      interval: weekly
    reviewers:
      - thymesave/silverware
