fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
        exclude: tsconfig.*\.json
      - id: pretty-format-json
        exclude: (tsconfig|package|ng-package|angular).*\.json
        args: [
            --autofix
        ]
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-case-conflict
      - id: check-toml
      - id: check-xml
      - id: fix-byte-order-marker
      - id: destroyed-symlinks

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: circleci-config-validate
      - id: shellcheck
        additional_dependencies: []

  - repo: https://github.com/matthorgan/pre-commit-conventional-commits
    rev: 20fb963
    hooks:
      - id: conventional-commit-check
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: ng-lint
        name: Run ng lint
        entry: .hooks/lint
        language: script
        files: '.*\.(ts|js)$'

