version: '2.1'

orbs:
  node: circleci/node@4.7.0
  browser-tools: circleci/browser-tools@1.2.3

executors:
  node:
    docker:
      - image: cimg/node:16.13.0-browsers

commands:
  remove_node_orb_lock:
    steps:
      - run:
          name: Remove lock files
          command: |
            rm /tmp/node-project-package.json
            rm /tmp/node-project-lockfile
  install_dependencies:
    steps:
      - node/install-packages
      - remove_node_orb_lock
      - node/install-packages:
          app-dir: projects/thymesave/core
      - remove_node_orb_lock
      - node/install-packages:
          app-dir: projects/thymesave/ingredients
      - remove_node_orb_lock
      - node/install-packages:
          app-dir: projects/thymesave/plugin
      - remove_node_orb_lock
      - node/install-packages:
          app-dir: projects/thymesave/translations

jobs:
  test:
    executor: node
    steps:
      - checkout
      - install_dependencies
      - browser-tools/install-chrome
      - run:
          name: Run ng lint
          command: npm run lint
      - run:
          name: Run ng test
          environment:
            NPM_ARGS: '-- --watch=false --browsers=ChromeHeadless --code-coverage'
          command: |
            npm run test @thymesave/core ${NPM_ARGS}
            npm run test @thymesave/translations ${NPM_ARGS}
            npm run test @thymesave/ingredients ${NPM_ARGS}
            npm run test @thymesave/plugin ${NPM_ARGS}
            npm run test ${NPM_ARGS}
      - run:
          name: Upload coverage to codecov.io
          command: bash <(curl -s https://codecov.io/bash)
  generate-translation-report:
    executor: node
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Run translation report script
          command: |
            ./scripts/translation-script/run
  build:
    executor: node
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Build
          environment:
            NPM_ARGS: ''
          command: |
            npm run build @thymesave/core ${NPM_ARGS}
            npm run build @thymesave/translations ${NPM_ARGS}
            npm run build @thymesave/ingredients ${NPM_ARGS}
            npm run build @thymesave/plugin ${NPM_ARGS}
            npm run build ${NPM_ARGS}
      - store_artifacts:
          path: ./dist
          destination: dist
      - persist_to_workspace:
          paths:
            - ./dist
          root: .

workflows:
  continious:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
