version: '2.1'

orbs:
  node: circleci/node@4.7.0
  browser-tools: circleci/browser-tools@1.2.3

executors:
  node:
    docker:
      - image: cimg/node:16.13.0-browsers

commands:
  install_dependencies:
    steps:
      - node/install-packages
      - node/install-packages:
          app-dir: projects/thymesave/core
      - node/install-packages:
          app-dir: projects/thymesave/ingredients
      - node/install-packages:
          app-dir: projects/thymesave/plugin
      - node/install-packages:
          app-dir: projects/thymesave/translations

jobs:
  test:
    executor: node
    steps:
      - checkout
      - install_dependencies
      - browser-tools/install-chrome
      - run:
          name: Run ng test
          command: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
      - run:
          name: Upload coverage to codecov.io
          command: bash <(curl -s https://codecov.io/bash)
  build:
    executor: node
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: ./dist
          destination: dist
      - persist_to_workspace:
          paths:
            - ./dist
          root: .

workflows:
  continious:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
