version: '2.1'

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1

executors:
  node:
    docker:
      - image: cimg/node:20.1.0-browsers

commands:
  attach_artifacts:
    steps:
      - attach_workspace:
          at: .
  remove_node_orb_lock:
    steps:
      - run:
          name: Remove lock files
          command: |
            rm /tmp/node-project-package.json || true
            rm /tmp/node-project-lockfile || true
  install_dependencies:
    steps:
      - node/install-packages
      - remove_node_orb_lock
      - node/install-packages:
          app-dir: projects/thymesave/ingredients
      - remove_node_orb_lock
      - node/install-packages:
          app-dir: projects/thymesave/plugin
      - remove_node_orb_lock
      - node/install-packages:
          app-dir: projects/thymesave/translations
      - remove_node_orb_lock
      - node/install-packages:
          app-dir: scripts/translation-report
      - remove_node_orb_lock

jobs:
  test:
    executor: node
    steps:
      - checkout
      - browser-tools/install-chrome
      - attach_artifacts
      - run:
          name: Run ng lint
          command: npm run lint
      - run:
          name: Run ng test
          environment:
            NPM_ARGS: '-- --watch=false --browsers=ChromeHeadless --code-coverage'
          command: |
            npm run test @thymesave/core ${NPM_ARGS}
            npm run test @thymesave/translations ${NPM_ARGS}
            npm run test @thymesave/ingredients ${NPM_ARGS}
            npm run test @thymesave/plugin ${NPM_ARGS}
            npm run test ${NPM_ARGS}
      - run:
          name: Upload coverage to codecov.io
          command: bash <(curl -s https://codecov.io/bash)
  generate-translation-report:
    executor: node
    steps:
      - checkout
      - attach_artifacts
      - run:
          name: Run translation report script
          command: |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
            npm install -g typescript
            npm run generate-translation-report
      - store_artifacts:
          path: scripts/translation-report/report.html
          destination: reports/translations.html
      - store_artifacts:
          path: scripts/translation-report/report.json
          destination: reports/translations.json
  build:
    executor: node
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Build
          command: |
            npm run build
      - store_artifacts:
          path: ./dist
          destination: dist
      - persist_to_workspace:
          paths:
            - ./dist
            - ./projects/thymesave/*/node_modules
            - ./node_modules
          root: .

workflows:
  continuous:
    jobs:
      - generate-translation-report:
          requires:
            - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
