#!/bin/bash
set -ex

root="${PWD}"

echo "[BUILD] Build generate-translations architect ..."
cd projects/thymesave/translations/generate-translations-report
npm link ../../../../dist/thymesave/core
tsc

echo "[BUILD] Build generate-ingredient architect ..."
cd "${root}/projects/thymesave/ingredients/"
npm link ../../../dist/thymesave/core
cd generate-ingredient-report
npm link ../../../../dist/thymesave/core
tsc

echo "[BUILD] Compile report script ..."
cd "${root}"
tsc

echo "[RUN  ] Generating json reports ..."
cd "${root}"
npx ng run @thymesave/translations:generate-report
npx ng run @thymesave/ingredients:generate-report

echo "[RUN  ] Run report generation ..."
cd "$(dirname "${BASH_SOURCE[0]}")"
npm i
tsc
node index.js
