#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"
cd ../..
root="${PWD}/"
set -ex

echo "[META] Using root folder ${root}"

echo "[BUILD] Build generate-translations architect ..."
# Link core to translations
cd "${root}projects/thymesave/translations/"
npm link ${root}dist/thymesave/core
# Link core to translations report generator
cd "${root}projects/thymesave/translations/generate-translations-report"
npm link ${root}dist/thymesave/core
# Compile script
tsc

echo "[BUILD] Build generate-ingredient architect ..."
# Link core to ingredients
cd "${root}projects/thymesave/ingredients/"
npm link ${root}dist/thymesave/core
# Link core to ingredient report generator
cd generate-ingredient-report
npm link ${root}dist/thymesave/core
# Compile script
tsc

echo "[BUILD] Compile report script ..."
cd "${root}"
tsc

echo "[RUN  ] Generating json reports ..."
cd "${root}"
npx ng run @thymesave/translations:generate-report
npx ng run @thymesave/ingredients:generate-report

echo "[RUN  ] Run report generation ..."
cd "$(dirname "${BASH_SOURCE[0]}")"
npm i
tsc
node index.js
